apiVersion: v1
kind: Service
metadata:
  name: nextcloud-nginx
  namespace: ##__NAMESPACE__##
  labels:
    app: nextcloud
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  type: LoadBalancer
  selector:
    app: nextcloud
    tier: webservice


