apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nextcloud-nginx
  namespace: ##__NAMESPACE__##
  labels:
    app: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
      tier: webservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
        tier: webservice
    spec:
      containers:
      - image: nextcloud:fpm
        name: nextcloud-fpm
        ports:
        - containerPort: 8080
          name: nextcloud
        - containerPort: 9000
          name: php
        volumeMounts:
        - name: nextcloud-custom-apps
          mountPath: /var/www/html/custom_apps
        - name: nextcloud-config
          mountPath: /var/www/html/config
        - name: nextcloud-data
          mountPath: /var/www/html/data
        - name: nextcloud-html
          mountPath: /var/www/html
      - image: certbot/certbot
        name: certbot
        command: ["sleep"]
        args: ["1d"]
#        command: ["/bin/sh"]
#        args:
#        - -c
#        - "certbot certonly --webroot -w /var/www/acme-challenge -d nextcloud.dev.martintim.com -d office.dev.martintim.com && while [ true ] ; do certbot renew --dry-run ; sleep 600s; done;"
        volumeMounts:
        - name: acmeChallenge
          mountPath: /var/www/acme-challenge
        - name: certs
          mountPath: /etc/letsencrypt/live/
      - image: nginx:latest
        name: nginx
        livenessProbe:
          httpGet:
            path: /.liveness
            port: 80
        ports:
        - containerPort: 80
          name: nginx-http
        - containerPort: 443
          name: nginx-https
        volumeMounts:
        - name: nextcloud-custom-apps
          mountPath: /var/www/html/custom_apps
          readOnly: true
        - name: nextcloud-config
          mountPath: /var/www/html/config
          readOnly: true
        - name: nextcloud-data
          mountPath: /var/www/html/data
          readOnly: true
        - name: nextcloud-html
          mountPath: /var/www/html/
          readOnly: true
        - name: nginx-config-map
          mountPath: /etc/nginx/conf.d/
        - name: certs
          mountPath: /etc/nginx/ssl/certs/
          readOnly: true
        - name: dhparam
          mountPath: /etc/nginx/ssl/dhparam/
          readOnly: true
        - name: acmeChallenge
          mountPath: /etc/nginx/ssl/acme-challenge/
          readOnly: true
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-pass
              key: password
        lifecycle:
          postStart:
            exec:
              command:
              - bash
              - "-c"
              - | 
                sleep 15
                whoami
                echo $MYSQL_ROOT_PASSWORD
                echo $NEXTCLOUD_ADMIN_PASSWORD                
                www-data
      volumes:
      - name: nginx-config-map
        configMap:
          name: nginx-config
      - name: nextcloud-custom-apps
        emptyDir: {}
      - name: nextcloud-config
        emptyDir: {}
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-persistent-data
      - name: nextcloud-html
        emptyDir: {}
      - name: nginx-certs
        secret:
          secretName: nextcloud-cert
      - name: certs
        emptyDir: {}
      - name: dhparam
        secret:
          secretName: dhparam-nginx
      - name: acmeChallenge
        emptyDir: {}
