apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nextcloud-nginx
  namespace: ##__NAMESPACE__##
  labels:
    app: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
      tier: webservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
        tier: webservice
    spec:
      containers:
      - image: nextcloud:fpm
        name: nextcloud-fpm
        ports:
        - containerPort: 8080
          name: nextcloud
        - containerPort: 9000
          name: php
        volumeMounts:
        - name: nextcloud-custom-apps
          mountPath: /var/www/html/custom_apps
        - name: nextcloud-config
          mountPath: /var/www/html/config
        - name: nextcloud-data
          mountPath: /var/www/html/data
        - name: nextcloud-html
          mountPath: /var/www/html
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-pass
              key: password
        lifecycle:
          postStart:
            exec:
              command:
              - bash
              - "-c"
              - |
                sleep 45s
                chsh -s /bin/bash www-data
                chown -R www-data:www-data /var/www/html/
                su www-data -c "php occ maintenance:install --database \"mysql\" --database-name \"nextcloud\"  --database-user \"root\" --database-pass $MYSQL_ROOT_PASSWORD --admin-user \"admin\" --admin-pass $NEXTCLOUD_ADMIN_PASSWORD --database-host \"nextcloud-mysql:3306\""
                su www-data -c "php occ config:system:set trusted_domains 1 --value=##__DOMAIN1__##"
                su www-data -c "php occ config:system:set trusted_domains 2 --value=##__DOMAIN2__##"
                su www-data -c "php occ app:enable richdocuments"
                su www-data -c "php occ config:app:set richdocuments wopi_url --value \"https://##__DOMAIN2__##\""
                su www-data -c "php occ user:setting admin settings email \"##__EMAIL__##\""
      - image: certbot/certbot
        name: certbot
#        command: ["sleep"]
#        args:
#        - 30d
        command: ["/bin/sh"]
        args:
        - -c
        - "sleep 600s && certbot certonly --webroot --agree-tos --email ##__EMAIL__## -w /var/www/acme-challenge -d ##__DOMAIN1__## -d ##__DOMAIN2__## && cp -rL /etc/letsencrypt/live/* /etc/certs/ && while [ true ] ; do certbot renew ; cp -rL /etc/letsencrypt/live/* /etc/certs/; sleep 12h; done;"
        volumeMounts:
        - name: acme-challenge
          mountPath: /var/www/acme-challenge
        - name: certs
          mountPath: /etc/certs/
        lifecycle:
          postStart:
            exec:
              command: 
              - "/bin/sh"
              - "-c"
              - | 
                mkdir -p /etc/certs/##__DOMAIN1__##
                openssl req -x509 -newkey rsa:4096 -keyout /etc/certs/##__DOMAIN1__##/privkey.pem -out /etc/certs/##__DOMAIN1__##/fullchain.pem -nodes -subj "/C=DE/ST=Bavaria/L=Munich/O=jmj-works.com/OU=nextcloud self signing/CN=##__DOMAIN1__##"
      - image: nginx:latest
        name: nginx
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          httpGet:
            path: /.liveness
            port: 80
        ports:
        - containerPort: 80
          name: nginx-http
        - containerPort: 443
          name: nginx-https
        volumeMounts:
        - name: nextcloud-custom-apps
          mountPath: /var/www/html/custom_apps
          readOnly: true
        - name: nextcloud-config
          mountPath: /var/www/html/config
          readOnly: true
        - name: nextcloud-data
          mountPath: /var/www/html/data
          readOnly: true
        - name: nextcloud-html
          mountPath: /var/www/html/
          readOnly: true
        - name: nginx-config-map
          mountPath: /etc/nginx/conf.d/
        - name: certs
          mountPath: /etc/nginx/ssl/certs/
          readOnly: false
        - name: dhparam
          mountPath: /etc/nginx/ssl/dhparam/
          readOnly: true
        - name: acme-challenge
          mountPath: /etc/nginx/ssl/acme-challenge/
          readOnly: true
        command: ["/bin/sh"]
        args:
        - -c
        - "nginx && sleep 660s && while [ true ] ; do nginx -s reload ; sleep 62m ; done ;"
      volumes:
      - name: nginx-config-map
        configMap:
          name: nginx-config
      - name: nextcloud-custom-apps
        emptyDir: {}
      - name: nextcloud-config
        emptyDir: {}
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-persistent-data
      - name: nextcloud-html
        emptyDir: {}
      - name: dhparam
        secret:
          secretName: dhparam-nginx
      - name: acme-challenge
        emptyDir: {}
      - name: certs
        emptyDir: 
          medium: "Memory"
